const copy = {
  en: {
    skip: "Skip to the idea machine", combinations: "possible combinations", saved: "Saved", eyebrow: "BEAT THE CREATIVE BLOCK",
    heroLine1: "Your next game", heroLine2: "starts right here.", heroText: "Leave the genre, mechanics and rules to chance. Spin the reels, catch strange combinations and discover your next game idea.", orPull: "or pull the lever",
    machineTitle: "Game idea machine", lockHint: "Lock the reels you love and spin the rest again.", newIdea: "GENERATE A NEW IDEA", spin: "SPIN THE MACHINE",
    generatedIdea: "GENERATED IDEA", inThisGame: "IN THIS GAME...", initialTitle: "Spin the reels and create your first game idea.", initialDescription: "Eight creative components will combine into an original starting point.", saveIdea: "SAVE IDEA", copy: "COPY",
    howLabel: "HOW DOES IT WORK?", howLine1: "Turn chance into", howLine2: "a design tool.", step1Title: "Spin", step1Text: "The machine builds a random combination from thousands of creative pieces.", step2Title: "Lock", step2Text: "Keep the components you like and spin the remaining reels again.", step3Title: "Develop", step3Text: "Copy or save the idea, then bring it to life with your own interpretation.",
    collection: "COLLECTION", savedIdeas: "Saved ideas", undo: "UNDO", footerText: "Great games start with an idea. The weird ones are usually better.",
    ready: "READY", generating: "GENERATING", ideaReady: "IDEA READY", allLocked: "All reels are locked — unlock at least one", spinFirst: "Spin the machine first", alreadySaved: "This idea is already saved", added: "Idea added to your collection", copied: "Idea copied to clipboard", copyFailed: "Clipboard permission denied", soundOn: "Sound effects on", soundOff: "Sound effects off", deleted: "Idea deleted", restored: "Idea restored", savedDone: "SAVED",
    emptyTitle: "No ideas yet.", emptyText: "Spin the machine and save the ideas you love here.", delete: "DELETE", closeSaved: "Close saved ideas", soundLabel: "Toggle sound effects", switchLanguage: "Türkçe diline geç", home: "Game Design Slot Machine home", lockReel: "Lock {label} reel", unlockReel: "Unlock {label} reel"
  },
  tr: {
    skip: "Fikir makinesine geç", combinations: "olası kombinasyon", saved: "Kayıtlar", eyebrow: "YARATICI TIKANIKLIĞA SON",
    heroLine1: "Bir sonraki oyunun", heroLine2: "burada başlıyor.", heroText: "Türü, mekaniği ve kuralları şansa bırak. Makaraları çevir, tuhaf kombinasyonları yakala, kendi oyun fikrini keşfet.", orPull: "veya kolu çek",
    machineTitle: "Oyun fikri makinesi", lockHint: "Beğendiğin makarayı kilitle, diğerlerini yeniden çevir.", newIdea: "YENİ FİKİR ÜRET", spin: "MAKİNEYİ ÇEVİR",
    generatedIdea: "ÇIKAN FİKİR", inThisGame: "BU OYUNDA...", initialTitle: "Makaraları çevir ve ilk oyun fikrini oluştur.", initialDescription: "Sekiz farklı yaratıcı bileşen birleşerek sana özgün bir başlangıç noktası verecek.", saveIdea: "FİKRİ KAYDET", copy: "KOPYALA",
    howLabel: "NASIL ÇALIŞIR?", howLine1: "Tesadüfü tasarım", howLine2: "aracına dönüştür.", step1Title: "Çevir", step1Text: "Makine, binlerce yaratıcı parçadan rastgele bir kombinasyon kurar.", step2Title: "Kilitle", step2Text: "Sevdiğin bileşenleri tut, geri kalan makaraları yeniden çevir.", step3Title: "Geliştir", step3Text: "Çıkan fikri kopyala, kaydet ve kendi yorumunla hayata geçir.",
    collection: "KOLEKSİYON", savedIdeas: "Kayıtlı fikirler", undo: "GERİ AL", footerText: "İyi oyunlar bir fikirle başlar. Garip olanlar genelde daha iyidir.",
    ready: "HAZIR", generating: "ÜRETİLİYOR", ideaReady: "FİKİR HAZIR", allLocked: "Tüm makaralar kilitli — en az birinin kilidini aç", spinFirst: "Önce makineyi çevir", alreadySaved: "Bu fikir zaten kayıtlı", added: "Fikir koleksiyonuna eklendi", copied: "Fikir panoya kopyalandı", copyFailed: "Kopyalama izni alınamadı", soundOn: "Ses efektleri açık", soundOff: "Ses efektleri kapalı", deleted: "Fikir silindi", restored: "Fikir geri getirildi", savedDone: "KAYDEDİLDİ",
    emptyTitle: "Henüz fikir yok.", emptyText: "Makineyi çevir ve sevdiğin fikirleri buraya kaydet.", delete: "SİL", closeSaved: "Kayıtlı fikirleri kapat", soundLabel: "Ses efektlerini aç veya kapat", switchLanguage: "Switch language to English", home: "Fikirhane ana sayfa", lockReel: "{label} makarasını kilitle", unlockReel: "{label} makarasının kilidini aç"
  }
};

const categories = [
  { key: "genre", label: { en: "GENRE", tr: "TÜR" }, items: [
    ["Roguelike adventure","Roguelike macera"],["Puzzle platformer","Bulmaca-platform"],["Tactical RPG","Taktiksel RPG"],["Rhythm game","Ritim oyunu"],["Survival game","Hayatta kalma"],["Social simulation","Sosyal simülasyon"],["Detective mystery","Dedektiflik"],["City builder","Şehir kurma"],["Tower defense","Kule savunma"],["Deckbuilder","Kart destesi kurma"],["Co-op horror","Kooperatif korku"],["Cozy farming","Rahat çiftçilik"],["Automation game","Otomasyon"],["Arena action","Arena aksiyon"],["Walking simulator","Yürüyüş simülasyonu"],["Metroidvania","Metroidvania"],["Physics comedy","Fizik tabanlı komedi"],["Stealth game","Gizlilik"],["Racing game","Yarış"],["Resource management","Kaynak yönetimi"],["Narrative adventure","Narratif macera"],["Asymmetric multiplayer","Asimetrik çok oyunculu"],["Incremental game","Incremental oyun"],["Party game","Parti oyunu"]
  ]},
  { key: "mechanic", label: { en: "CORE MECHANIC", tr: "ANA MEKANİK" }, items: [
    ["Rewind time","Zamanı geri sar"],["Turn shadows into objects","Gölgeleri nesne yap"],["Fold the world","Dünyayı katla"],["Steal enemy abilities","Düşmanların yeteneğini çal"],["Navigate through sound","Sesle yön bul"],["Change rules with cards","Kuralları kartlarla değiştir"],["Rotate gravity","Yerçekimini döndür"],["Control two characters at once","İki karakteri aynı anda yönet"],["Trade memories","Anıları takas et"],["Mix colors","Renkleri karıştır"],["Draw the map into existence","Haritayı çizerek oluştur"],["Link objects together","Nesneleri birbirine bağla"],["Change your size","Boyut değiştir"],["Fight through dialogue","Diyalogla savaş"],["Travel between dreams","Rüyalar arasında geçiş yap"],["Turn mistakes into advantages","Hataları avantaja çevir"],["Program your clones","Klonlarını programla"],["Build chain reactions","Zincirleme reaksiyon kur"],["Redirect light","Işığı yönlendir"],["Learn through a time loop","Zaman döngüsü öğren"],["Transform the world through rhythm","Çevreyi ritimle dönüştür"],["Enter the enemy's perspective","Düşmanın bakış açısına geç"],["Turn words into physical objects","Kelimeleri fiziksel nesne yap"],["Build power by taking risks","Risk alarak güç biriktir"]
  ]},
  { key: "setting", label: { en: "SETTING", tr: "MEKÂN" }, items: [
    ["An abandoned space amusement park","Terk edilmiş uzay lunaparkı"],["The back of a colossal creature","Dev bir canlının sırtı"],["A flooded Istanbul","Sular altında kalmış İstanbul"],["An endless night train","Sonsuz gece treni"],["A marketplace above the clouds","Bulutların üstündeki pazar"],["A self-repairing castle","Kendi kendini onaran kale"],["A miniature apartment building","Minyatür bir apartman"],["Customs between dreams","Rüyalar arası gümrük kapısı"],["A walking desert city","Çölde yürüyen şehir"],["A cosmic tea garden","Kozmik bir çay bahçesi"],["A museum outside time","Zamanın dışındaki müze"],["Inside a living computer","Canlı bir bilgisayarın içi"],["An archive beneath the polar ice","Kutup altındaki arşiv"],["A radio station full of ghosts","Hayaletlerle dolu radyo istasyonu"],["A forest growing backwards","Tersine büyüyen orman"],["A neighborhood store on Mars","Mars'taki mahalle bakkalı"],["The office of forgotten gods","Unutulmuş tanrıların ofisi"],["A school that opens by moonlight","Ay ışığında açılan okul"],["The last library on Earth","Dünyanın son kütüphanesi"],["A pirate's mechanical whale","Bir korsanın mekanik balinası"],["A shape-shifting hotel","Sürekli şekil değiştiren otel"],["A kitchen built for giants","Devlerin mutfağı"],["The orbit of a dead star","Ölü bir yıldızın çevresi"],["A harbor where memories are stored","Anıların depolandığı liman"]
  ]},
  { key: "goal", label: { en: "GOAL", tr: "AMAÇ" }, items: [
    ["Find a missing day","Kaybolan bir günü bul"],["Make the last customer happy","Son müşteriyi mutlu et"],["Wake the city without making a sound","Şehri sessizce uyandır"],["Repair a broken friendship","Kırık bir dostluğu onar"],["Restart the sun","Güneşi yeniden çalıştır"],["Prove your identity","Kimliğini kanıtla"],["Delay the disaster a little each turn","Felaketi her tur biraz geciktir"],["Invent a way home","Eve giden yolu icat et"],["Earn the monster's trust","Canavarın güvenini kazan"],["Keep a secret from everyone","Bir sırrı herkesten sakla"],["Save the shop before it closes","Kapanmadan önce dükkânı kurtar"],["Train the person who will replace you","Kendi yerine geçecek kişiyi eğit"],["Reconcile two enemy societies","İki düşman toplumu barıştır"],["Restore a place erased from the map","Haritadan silinen yeri geri getir"],["Finish the final song","Son şarkıyı tamamla"],["Prove the prophecy wrong","Kehaneti yanlış çıkar"],["Stop a wedding without sabotaging it","Bir düğünü sabote etmeden durdur"],["Teach curiosity to an AI","Yapay zekâya merak öğret"],["Bring back the missing season","Kayıp mevsimi geri getir"],["Pay your debts through strange jobs","Borçlarını tuhaf görevlerle öde"],["Seal every exit","Bütün çıkışları kapat"],["Save the thing hunting you","Kendini avlayan şeyi kurtar"],["Create a legend from scratch","Bir efsaneyi sıfırdan üret"],["Broadcast the truth before dawn","Gece bitmeden gerçeği yayınla"]
  ]},
  { key: "constraint", label: { en: "RULE / CONSTRAINT", tr: "YASAK / KISIT" }, items: [
    ["You cannot harm anyone","Kimseye zarar veremezsin"],["You cannot repeat the same move","Aynı hareketi iki kez yapamazsın"],["No numbers may appear on screen","Ekranda sayı gösterilemez"],["Speaking is forbidden","Konuşmak yasak"],["Time advances only when you stop","Durduğunda zaman ilerler"],["Every choice destroys an item","Her seçim bir eşyayı yok eder"],["You cannot look at the map","Haritaya bakamazsın"],["You can never go back","Geri dönemezsin"],["You grow stronger only when failing","Yalnızca başarısızken güçlenirsin"],["You cannot open any doors","Hiçbir kapıyı açamazsın"],["Your character cannot lie","Karakterin yalan söyleyemez"],["You cannot move in the light","Işıkta hareket edemezsin"],["You may carry only one item","Envanterinde tek eşya taşırsın"],["Defeating enemies makes the game harder","Düşmanları yenmek oyunu zorlaştırır"],["You cannot trust the same person twice","Aynı kişiye iki kez güvenemezsin"],["Running ages the world","Koşmak dünyayı yaşlandırır"],["Saving erases one of your memories","Kaydetmek bir anını siler"],["Money is forbidden","Para kullanmak yasak"],["There is no direct control","Doğrudan kontrol yok"],["One button disappears each level","Her bölümde bir tuş kaybolur"],["You shrink every time you win","Kazandıkça karakter küçülür"],["No quest text is shown","Görev metni gösterilmez"],["You are not allowed to break anything","Hiçbir şeyi kırmana izin yok"],["Your decisions cannot be undone","Kararlarını geri alamazsın"]
  ]},
  { key: "twist", label: { en: "WILDCARD", tr: "SÜRPRİZ DOKUNUŞ" }, items: [
    ["The narrator is afraid of you","Anlatıcı senden korkuyor"],["The final boss is the menu itself","Final boss aslında menü"],["NPCs remember previous runs","NPC'ler önceki denemeleri hatırlıyor"],["The map changes when unseen","Harita sen bakmazken değişiyor"],["Players see different realities","Oyuncular farklı gerçeklikler görüyor"],["Losing advances the story","Kaybetmek hikâyeyi ilerletiyor"],["Items have agendas of their own","Eşyaların kendi gündemleri var"],["Enemies ask you for help","Düşmanlar senden yardım istiyor"],["The genre changes at night","Oyunun türü gece değişiyor"],["The credits are a playable level","Jenerik oynanabilir bir bölüm"],["Your character is not the villain","Kontrol ettiğin kişi kötü karakter değil"],["Choices emerge from your behavior","Seçenekler davranışlarından üretiliyor"],["The world ages in real time","Dünya gerçek saate göre yaşlanıyor"],["Your shadows act independently","Gölgelerin senden bağımsız"],["The boss fight is a job interview","Boss savaşı bir iş görüşmesi"],["The tutorial is the final level","Öğretici bölüm son bölüm"],["The save file is part of the story","Kayıt dosyası hikâyenin parçası"],["Silence is an invisible enemy","Sessizlik görünmez bir düşman"],["Side quests rewrite the main world","Yan görevler ana dünyayı yeniden yazar"],["The player is another character's inner voice","Oyuncu ikinci bir karakterin iç sesi"],["Every victory creates trouble for another player","Her zafer başka bir oyuncuya sorun yaratır"],["Music foreshadows upcoming events","Müzik yaklaşan olayları önceden söyler"],["Bugs become permanent world features","Hatalar kalıcı dünya özelliklerine dönüşür"],["The camera is an unreliable character","Kamera güvenilmez bir karakter"]
  ]},
  { key: "style", label: { en: "VISUAL STYLE", tr: "GÖRSEL STİL" }, items: [
    ["Two-color pixel art","İki renkli piksel art"],["Hand-drawn sketchbook","El çizimi eskiz defteri"],["1990s cartoon","90'lar çizgi filmi"],["Clay animation","Kil animasyon"],["Neon noir","Neon-noir"],["Vintage children's book","Eski çocuk kitabı"],["Brutalist collage","Brütalist kolaj"],["Low-poly diorama","Düşük poligonlu diorama"],["Watercolor fairytale","Suluboya masal"],["CRT terminal aesthetic","CRT terminal estetiği"],["Miniature model set","Minyatür maket"],["Monochrome engraving","Tek renkli gravür"],["Stained glass","Renkli cam vitray"],["Retro sci-fi poster","Retro bilimkurgu afişi"],["Paper puppet theater","Kağıt kukla tiyatrosu"],["Analog photography","Analog fotoğraf"],["Isometric toy box","İzometrik oyuncak kutusu"],["Surreal dream journal","Sürreal rüya günlüğü"],["VHS found footage","VHS found-footage"],["Ottoman miniature inspired","Osmanlı minyatürü esintili"],["Minimal geometry","Minimal geometrik"],["Dark fairytale","Karanlık masal"],["Pastel solarpunk","Pastel solarpunk"],["Y2K digital kitsch","Y2K dijital kitsch"]
  ]},
  { key: "mood", label: { en: "MOOD", tr: "HİSSİYAT" }, items: [
    ["Melancholic yet hopeful","Hüzünlü ama umutlu"],["Tense and paranoid","Gergin ve paranoyak"],["Warm and cozy","Sıcacık ve rahat"],["Delightfully absurd","Absürt derecede komik"],["Slow and meditative","Yavaş ve meditatif"],["Chaotic but joyful","Kaotik ama neşeli"],["Uncanny and intriguing","Tekinsiz ve merak uyandırıcı"],["Epic and lonely","Destansı ve yalnız"],["Romantic and mysterious","Romantik ve gizemli"],["Nostalgic","Nostaljik"],["Constantly surprising","Sürekli şaşırtıcı"],["Competitive and energetic","Rekabetçi ve enerjik"],["Thoughtful","Düşünceli"],["Darkly humorous","Karanlık mizahlı"],["Whimsical","Masalsı"],["Claustrophobic","Klostrofobik"],["Optimistic","İyimser"],["Melancholic","Melankolik"],["Strange but lovable","Tuhaf ama sevimli"],["Rebellious","İsyankâr"],["Soothing","Rahatlatıcı"],["Urgent","Aciliyet dolu"],["Mysterious","Gizemli"],["Cute and creepy","Tatlı-ürkütücü"]
  ]}
];

const systemLanguage = (navigator.languages || [navigator.language]).some(language => language.toLowerCase().startsWith("tr")) ? "tr" : "en";
const state = { lang: localStorage.getItem("game-design-slot-language") || systemLanguage, selected: {}, locked: new Set(), spinning: false, ideaNo: 0, sound: true, saved: loadSaved() };
const els = {
  reels: document.querySelector("#reels"), machine: document.querySelector("#machine"), spin: document.querySelector("#spinButton"), status: document.querySelector("#statusText"), title: document.querySelector("#resultTitle"), description: document.querySelector("#resultDescription"), card: document.querySelector(".idea-card"), number: document.querySelector("#ideaNumber"), save: document.querySelector("#saveButton"), copy: document.querySelector("#copyButton"), savedCount: document.querySelector("#savedCount"), savedButton: document.querySelector("#savedButton"), panel: document.querySelector("#savedPanel"), list: document.querySelector("#savedList"), toast: document.querySelector("#toast"), toastMessage: document.querySelector("#toastMessage"), undo: document.querySelector("#undoButton"), sound: document.querySelector("#soundButton"), language: document.querySelector("#languageButton")
};

function t(key) { return copy[state.lang][key]; }
function itemFor(category, index) { return category.items[index][state.lang === "en" ? 0 : 1]; }
function valueFor(key) { const category = categories.find(entry => entry.key === key); return itemFor(category, state.selected[key]); }
function loadSaved() { try { return JSON.parse(localStorage.getItem("game-design-slot-saved") || localStorage.getItem("fikirhane-saved")) || []; } catch { return []; } }
function persistSaved() { localStorage.setItem("game-design-slot-saved", JSON.stringify(state.saved)); renderSaved(); }
function randomIndex(length, except) { let index; do { index = Math.floor(Math.random() * length); } while (length > 1 && index === except); return index; }

function createReels() {
  els.reels.innerHTML = categories.map((category, index) => `
    <article class="reel" data-key="${category.key}">
      <div class="reel-header"><span>0${index + 1} // <b>${category.label[state.lang]}</b></span>
        <button class="lock-button" type="button" aria-label="${lockLabel(category, false)}" aria-pressed="false">
          <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>
        </button>
      </div><div class="reel-window"><span class="reel-value">—</span></div>
    </article>`).join("");
  els.reels.querySelectorAll(".lock-button").forEach(button => button.addEventListener("click", toggleLock));
}

function lockLabel(category, locked) { return t(locked ? "unlockReel" : "lockReel").replace("{label}", category.label[state.lang]); }
function toggleLock(event) {
  if (state.spinning) return;
  const reel = event.currentTarget.closest(".reel"); const key = reel.dataset.key; const category = categories.find(entry => entry.key === key);
  state.locked.has(key) ? state.locked.delete(key) : state.locked.add(key);
  const locked = state.locked.has(key); reel.classList.toggle("locked", locked); event.currentTarget.setAttribute("aria-pressed", String(locked)); event.currentTarget.setAttribute("aria-label", lockLabel(category, locked)); tone(locked ? 520 : 300, .05);
}

const combinationTotal = categories.reduce((total, category) => total * category.items.length, 1);
function applyLanguage() {
  document.documentElement.lang = state.lang; document.title = state.lang === "tr" ? "Fikirhane" : "Game Design Slot Machine";
  document.querySelector('meta[name="description"]').content = state.lang === "tr" ? "Tek çevirmede özgün oyun konseptleri üreten yaratıcı fikir makinesi." : "Generate original game concepts with a single spin.";
  document.querySelectorAll("[data-i18n]").forEach(element => { element.textContent = t(element.dataset.i18n); });
  document.querySelector("#brandName").textContent = state.lang === "tr" ? "FİKİRHANE" : "GAME DESIGN SLOT MACHINE"; document.querySelector("#brandLink").setAttribute("aria-label", t("home"));
  document.querySelector("#footerBrand").textContent = `${state.lang === "tr" ? "FİKİRHANE" : "GAME DESIGN SLOT MACHINE"} © 2026`;
  els.language.querySelector("span").textContent = state.lang === "tr" ? "EN" : "TR"; els.language.setAttribute("aria-label", t("switchLanguage")); els.sound.setAttribute("aria-label", t("soundLabel")); document.querySelector(".close-button").setAttribute("aria-label", t("closeSaved"));
  els.status.textContent = t(state.spinning ? "generating" : state.ideaNo ? "ideaReady" : "ready"); document.querySelector("#comboCount").textContent = new Intl.NumberFormat(state.lang === "tr" ? "tr-TR" : "en-US", { notation: "compact", maximumFractionDigits: 1 }).format(combinationTotal);
  document.querySelectorAll(".reel").forEach(reel => { const category = categories.find(entry => entry.key === reel.dataset.key); reel.querySelector(".reel-header b").textContent = category.label[state.lang]; reel.querySelector(".lock-button").setAttribute("aria-label", lockLabel(category, state.locked.has(category.key))); if (Number.isInteger(state.selected[category.key])) reel.querySelector(".reel-value").textContent = valueFor(category.key); });
  if (state.ideaNo) buildIdea(false); renderSaved();
}

function spin() {
  if (state.spinning) return; const active = categories.filter(category => !state.locked.has(category.key)); if (!active.length) return showToast(t("allLocked"));
  state.spinning = true; els.machine.classList.add("spinning"); els.spin.disabled = true; els.status.textContent = t("generating"); els.save.classList.remove("saved"); tone(180, .08);
  const reduced = matchMedia("(prefers-reduced-motion: reduce)").matches; const duration = reduced ? 80 : 1150; const timers = [];
  active.forEach((category, index) => { const reel = document.querySelector(`[data-key="${category.key}"]`); const value = reel.querySelector(".reel-value"); reel.classList.add("spinning"); timers.push(setInterval(() => { value.textContent = itemFor(category, randomIndex(category.items.length)); tone(110 + index * 18, .018, .012); }, reduced ? 60 : 70 + index * 4)); });
  setTimeout(() => active.forEach((category, index) => setTimeout(() => { const reel = document.querySelector(`[data-key="${category.key}"]`); clearInterval(timers[index]); state.selected[category.key] = randomIndex(category.items.length, state.selected[category.key]); reel.querySelector(".reel-value").textContent = itemFor(category, state.selected[category.key]); reel.classList.remove("spinning"); tone(360 + index * 45, .07); if (index === active.length - 1) { buildIdea(); finishSpin(); } }, reduced ? 0 : index * 105)), duration);
}

function finishSpin() { state.spinning = false; els.machine.classList.remove("spinning"); els.spin.disabled = false; els.status.textContent = t("ideaReady"); }
function lower(value) { return value.charAt(0).toLocaleLowerCase(state.lang === "tr" ? "tr-TR" : "en-US") + value.slice(1); }
function buildIdea(increment = true) {
  if (increment) state.ideaNo += 1; const v = Object.fromEntries(categories.map(category => [category.key, valueFor(category.key)]));
  if (state.lang === "tr") { els.title.textContent = `${v.mood} bir ${v.genre}: ${v.setting} mekânında ${lower(v.goal)}.`; els.description.textContent = `Oyunun kalbinde “${lower(v.mechanic)}” mekaniği var. Ancak bir kural her şeyi değiştiriyor: ${v.constraint}. Üstelik ${lower(v.twist)}. Tüm deneyim ${lower(v.style)} bir görsel dille sunuluyor.`; }
  else { els.title.textContent = `${v.mood} ${v.genre} set in ${lower(v.setting)}, where you must ${lower(v.goal)}.`; els.description.textContent = `At its core is the “${lower(v.mechanic)}” mechanic. But one rule changes everything: ${v.constraint}. And here's the twist: ${v.twist}. The whole experience is presented in a ${lower(v.style)} visual style.`; }
  els.number.textContent = `#${String(state.ideaNo).padStart(3,"0")}`; if (increment) { els.card.classList.remove("reveal"); void els.card.offsetWidth; els.card.classList.add("reveal"); tone(650, .12, .04); }
}

function currentIdea() { return { id: Date.now(), number: els.number.textContent, title: els.title.textContent, description: els.description.textContent, lang: state.lang }; }
function saveIdea() { if (!state.ideaNo) return showToast(t("spinFirst")); if (state.saved.some(item => item.title === els.title.textContent)) return showToast(t("alreadySaved")); state.saved.unshift(currentIdea()); persistSaved(); els.save.classList.add("saved"); const label = els.save.querySelector("span"); label.textContent = t("savedDone"); setTimeout(() => label.textContent = t("saveIdea"), 1400); showToast(t("added")); tone(720,.1); }
async function copyIdea(idea = currentIdea()) { if (!state.ideaNo && !idea.title) return showToast(t("spinFirst")); const brand = idea.lang === "tr" ? "FİKİRHANE" : "GAME DESIGN SLOT MACHINE"; const text = `${brand} ${idea.number}\n\n${idea.title}\n\n${idea.description}`; try { await navigator.clipboard.writeText(text); showToast(t("copied")); } catch { showToast(t("copyFailed")); } }
function renderSaved() { els.savedCount.textContent = state.saved.length; if (!state.saved.length) { els.list.innerHTML = `<div class="empty-state"><strong>${t("emptyTitle")}</strong>${t("emptyText")}</div>`; return; } els.list.innerHTML = state.saved.map(item => `<article class="saved-item" data-id="${item.id}"><small>${item.number} · ${(item.lang || "tr").toUpperCase()}</small><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.description)}</p><footer><button type="button" data-copy>${t("copy")}</button><button type="button" data-delete>${t("delete")}</button></footer></article>`).join(""); }
function escapeHtml(value) { const div = document.createElement("div"); div.textContent = value; return div.innerHTML; }
let panelTrigger;
function openPanel(open) { if (open) panelTrigger = document.activeElement; els.panel.classList.toggle("open", open); els.panel.setAttribute("aria-hidden", String(!open)); document.body.classList.toggle("panel-open", open); if (open) document.querySelector(".close-button").focus(); else panelTrigger?.focus(); }
function showToast(message, undoAction) { els.toastMessage.textContent = message; els.toast.classList.toggle("has-action", Boolean(undoAction)); els.toast.classList.add("show"); els.undo.onclick = undoAction ? () => { undoAction(); els.toast.classList.remove("show", "has-action"); } : null; clearTimeout(showToast.timer); showToast.timer = setTimeout(() => els.toast.classList.remove("show", "has-action"), undoAction ? 5000 : 2200); }

let audioContext;
function tone(frequency, duration = .04, volume = .02) { if (!state.sound) return; try { audioContext ||= new (window.AudioContext || window.webkitAudioContext)(); const oscillator = audioContext.createOscillator(); const gain = audioContext.createGain(); oscillator.type = "square"; oscillator.frequency.value = frequency; gain.gain.setValueAtTime(volume, audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(.0001, audioContext.currentTime + duration); oscillator.connect(gain).connect(audioContext.destination); oscillator.start(); oscillator.stop(audioContext.currentTime + duration); } catch {} }

els.spin.addEventListener("click", spin); els.save.addEventListener("click", saveIdea); els.copy.addEventListener("click", () => copyIdea()); els.savedButton.addEventListener("click", () => openPanel(true)); document.querySelectorAll("[data-close-panel]").forEach(element => element.addEventListener("click", () => openPanel(false)));
els.language.addEventListener("click", () => { state.lang = state.lang === "en" ? "tr" : "en"; localStorage.setItem("game-design-slot-language", state.lang); applyLanguage(); tone(560,.06); });
els.sound.addEventListener("click", () => { state.sound = !state.sound; els.sound.setAttribute("aria-pressed", String(state.sound)); showToast(t(state.sound ? "soundOn" : "soundOff")); if (state.sound) tone(500,.06); });
els.list.addEventListener("click", event => { const item = event.target.closest(".saved-item"); if (!item) return; const idea = state.saved.find(entry => String(entry.id) === item.dataset.id); if (event.target.matches("[data-copy]")) copyIdea(idea); if (event.target.matches("[data-delete]")) { const index = state.saved.findIndex(entry => entry.id === idea.id); state.saved.splice(index, 1); persistSaved(); showToast(t("deleted"), () => { state.saved.splice(index, 0, idea); persistSaved(); showToast(t("restored")); }); } });
document.addEventListener("keydown", event => { if (event.code === "Space" && !event.repeat && !["BUTTON","INPUT","TEXTAREA"].includes(document.activeElement.tagName) && !els.panel.classList.contains("open")) { event.preventDefault(); spin(); } if (event.key === "Escape" && els.panel.classList.contains("open")) openPanel(false); });

createReels(); applyLanguage(); renderSaved(); spin();
